### ISSUE TITLE
Inconsistent stream handling on IFileStorage.SaveFile() implementations

### ISSUE THREAD

**Issue by jlanning** [FoundatioFx/Foundatio#108]
The FolderFileStorage class calls  stream.Seek(0, SeekOrigin.Begin)  on the passed stream before copying the contents to the file stream.  While this might be convenient (in some cases), it is inconsistent with the other implementations of IFileStream (InMemoryStream and AzureFileStream).  And it seems presumptive to assume the caller did not positioned the stream correctly for the save operation and to "fix it for them".  I can't think of any stream handling functions that do this - including the underlying ones called by these classes: Stream.CopyTo() and CloudBlockBlob.UploadFromStream().

My recommendation is to remove the Seek() operation.

**Comment by niemyjski** [comment]
I can't remember why we did this, do all the tests pass if you remove the seek? If so, would you mind submitting a pr for this.

**Comment by ejsmith** [comment]
Yeah, I agree. The Seek's should not be in there.

**Comment by niemyjski** [comment]
We've fixed this issue :)
