### ISSUE TITLE
Support Aliyun OSS storage

### ISSUE THREAD

**Issue by edwardmeng** [FoundatioFx/Foundatio#110]
Recently when deploying exceptionless, in order to improve the scale out ability, we want to make use of cloud storage. Currently the Foundatio only support windows azure, but the Aliyun is with higher efficiency in China.
When we want to request pr to implement the adapter between Foundation and Aliyun OSS, there is no project for this purpose, and we don't know how to request pr for it.

**Comment by niemyjski** [comment]
Perhaps we should create a Foundatio.Alibaba project? Is there an easy way to test against there api?

**Comment by edwardmeng** [comment]
Could you please create the project? And then I can request pr.
There is free trial for developers for 6 months in aliyun.
https://intl.aliyun.com/campaign/free-trial?spm=5176.7973419.765261.8.6c8d8dda43WG0r

**Comment by niemyjski** [comment]
The repo has been created so I'm closing this issue. We need to update the readme in this repo once we get the integration done :)
