### ISSUE TITLE
How can i use Foundatio.Lock?

### ISSUE THREAD

**Issue by ccccccmd** [FoundatioFx/Foundatio#112]
It's like this ?

somecode  to get lockprovider

       var rediscco = new RedisCacheClientOptions() { ConnectionMultiplexer = muxer };

     _lockProvider = new CacheLockProvider(new RedisCacheClient(rediscco), new RedisMessageBus(new RedisMessageBusOptions() { Subscriber = rediscco.ConnectionMultiplexer.GetSubscriber() }));

some code to get lock

     public static  async Task<ILock> AcquireAsync(string name,
            TimeSpan? lockTimeout = null,
            CancellationToken cancellationToken = default(CancellationToken),
            bool continueOnCapturedContext = false)
        {
            var @lock = await _lockProvider.AcquireAsync(name, lockTimeout, cancellationToken)
                .ConfigureAwait(continueOnCapturedContext);
            return @lock;
        }
user lock

      var l = LockHelper.AcquireAsync(key, TimeSpan.FromSeconds(5)).Result ;   
      ............my code to process stock............
      l.ReleaseAsync();

**Comment by niemyjski** [comment]
That looks right, are you seeing some kind of issue?

**Comment by ccccccmd** [comment]
i find this project:
[https://github.com/IvanZheng/IFramework/tree/master/Src/iFramework.Plugins/IFramework.FoundatioLock](IFramework)

by the way,
two mechines have two  singleton  lockproviders,will it  lead to problems?

**Comment by niemyjski** [comment]
I suppose it could if you are locking on the same key inside of each other but I'm not sure without trying it. If you have a sample that can show off an issue that would be greatly appreciated.

**Comment by IvanZheng** [comment]
@ccccccmd IFramework.FoundatioLock is only used for single process, because it's in memory lock based on Foundatio. If you want to use for distributed system, you should use IFramework.FoundatioLockRedis which is based on Foundatio.Redis.

**Comment by niemyjski** [comment]
I'm going to close this issue, if you have any questions, please let us know.
