### ISSUE TITLE
The MessagePackSerializer should add a optional parameter to determine whether compress the serialized data.

### ISSUE THREAD

**Issue by edwardmeng** [FoundatioFx/Foundatio#118]
https://github.com/FoundatioFx/Foundatio/blob/14db27dd26f54ff63841629f115eac47b7d57b12/src/Foundatio/Serializer/MessagePackSerializer.cs

When the value of parameter 'compress' is set true, it should serialize/deserialize with `MessagePack.LZ4MessagePackSerializer.NonGeneric`, otherwise should use `MessagePack.MessagePackSerializer.NonGeneric`

**Comment by niemyjski** [comment]
Can you please submit a pr for this (probably would be good to have a quick test for it as well.
