### ISSUE TITLE
RedisMessageBus there is no effect

### ISSUE THREAD

**Issue by cuibty** [FoundatioFx/Foundatio#126]
```

IMessageBus messageBus = new RedisMessageBus(new RedisMessageBusOptions
{
    Subscriber = connectionMultiplexer.GetSubscriber()
});

await messageBus.SubscribeAsync<SimpleMessage>(msg =>
{
    Console.WriteLine(msg.Data);
});

await messageBus.PublishAsync(new SimpleMessage { Data = "Hello" });

```

**Comment by niemyjski** [comment]
What version of redis are you using? Are you using redis cluster support?

**Comment by cuibty** [comment]
reids v3.2.100 windows 

not use redis cluster

**Comment by cuibty** [comment]
![snipaste_2018-04-05_11-32-34](https://user-images.githubusercontent.com/12811343/38346029-1429d1ae-38c5-11e8-9885-b74f883456ca.png)

**Comment by niemyjski** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/1020579/38370227-3b31bafc-38af-11e8-887b-5c2c47b33a37.png">

I'm not able to reproduce, are you waiting long enough for the message to be delivered? Can you please attach a sample console app that reproduces what you are seeing.

**Comment by niemyjski** [comment]
I'm closing this to keep the issues clean as I haven't been able to reproduce. If you can attach a sample app that would be greatly appreciated!
