### ISSUE TITLE
HybridCacheClient cstr -> InMemoryCacheClient max cachekeys hardcoded to 100 items

### ISSUE THREAD

**Issue by peterrizk** [FoundatioFx/Foundatio#134]
Hi Guys,

Any reason why we can only have 100 keys in memory at once? Do you see any issues with overriding this number to be much larger in the future provided we increase the RAM appropriately?

Thanks in advance.
Peter.

**Comment by niemyjski** [comment]
We kept it at 100 due to memory concerns, if you have the ram bump it up :)
