### ISSUE TITLE
Feature - Adding shallow clone option to HybridCacheClient

### ISSUE THREAD

**Issue by iAgiler** [FoundatioFx/Foundatio#135]
Per my performance testing about HybridCacheClient.GetAsync(), DeepClonerGenerator's performance is very poor. Is it possible to adding an option like CloneOption.Shallow into class HybridCacheClient and then can force it to use shallow clone?  Because in most scenarios, we just use plain objects rather than nested objects for cache.

Following is the performance testing details, I included other options for reference:

**Option | calling times | total duration(ms) | ms per call**
1. HybridCacheClient（deep clone） | 10000 | 21422 | 2.1422
2. HybridCacheClient（shallow clone） | 1000000 | 1062 | 0.001062
3. HybridCacheClient（turn off clone） | 1000000 | 829 | 0.000829
4. .NET Core MemoryCache | 1000000 | 184 | 0.000184

**Comment by niemyjski** [comment]
I'm guessing you can run these tests against just our in memory cache client and get more accurate results. We deep clone because we don't want references to be modified (cache entries should be immutable) and we don't know what kind of objects they will be. Do you know what the .net core memory cache is doing?

**Comment by iAgiler** [comment]
> I'm guessing you can run these tests against just our in memory cache client and get more accurate results. We deep clone because we don't want references to be modified (cache entries should be immutable) and we don't know what kind of objects they will be. Do you know what the .net core memory cache is doing?

I have tested InMemoryCacheClient, it is same as HybridCacheClient. For MemoryCache under namespace System.Runtime.Caching, it returns cached entry's reference. Between cache contaminated and performance, I would prefer performance, because I consider performance is cache's main purpose.

**Comment by ejsmith** [comment]
Yeah, that makes sense. Maybe we should just make it an option then to turn the cloning completely off.

**Comment by niemyjski** [comment]
Where do we stand on this, from reading this it seems like we should add an option to the hybrid cache client. @iAgiler would you mind submitting a pr for this.

**Comment by niemyjski** [comment]
@iAgiler were you able to add a pr for this?

**Comment by ejsmith** [comment]
@iAgiler we added an option to the `InMemoryCacheClient` to allow turning cloning off. So you should be able to set that option on the `HybridCacheClient` now as well.
