### ISSUE TITLE
Docs For Foundatio

### ISSUE THREAD

**Issue by prince272** [FoundatioFx/Foundatio#141]
Hello,

Please are there docs for Foundatio. How to use it with Asp Core etc.

**Comment by niemyjski** [comment]
Hello,

Is there anything specific feature you are looking to use? We have an ASP.NET Core application here (https://github.com/exceptionless/Exceptionless) that uses Foundatio extensively.

**Comment by prince272** [comment]
Hello,

Oh no. I will take a look at the Exceptionless app. Thanks for your assistance.

**Comment by niemyjski** [comment]
Hello,

1. I'd recommend taking a look at our readme / tests for more on usage. If you have a specific question on usage let me know.
2. I'd cache anything that is expensive to call or is prone to failure. There are a lot of best practices guides on caching.
3. I'd scope it based on resource and unique id like `user:user_id_here`.

**Comment by prince272** [comment]
Thank you so much for your responds. I'll take note on that.

**Comment by prince272** [comment]
I really like this part: "*cache anything that is expensive to call or is
prone to failure."*
