### ISSUE TITLE
Question: How to deque or remove item from Redis queue?

### ISSUE THREAD

**Issue by lefig** [FoundatioFx/Foundatio#142]
Hi there,

I have been studying the Redis queue examples and can see where and how items are queued. But I am struggling to find some code sample showing item removal. I tried calling dequeueasync but this doesnt seem to work.

I would appreciate any help or thoughts.

**Comment by niemyjski** [comment]
When you call Dequeue it calls the following implementation which grabs the item from the redis queue (https://github.com/FoundatioFx/Foundatio.Redis/blob/master/src/Foundatio.Redis/Queues/RedisQueue.cs#L220 and https://github.com/FoundatioFx/Foundatio.Redis/blob/master/src/Foundatio.Redis/Queues/RedisQueue.cs#L325) which pops an item off a list. Then when you call complete (https://github.com/FoundatioFx/Foundatio.Redis/blob/master/src/Foundatio.Redis/Queues/RedisQueue.cs#L341) it removes the various keys from redis. 

You can think of it has having multiple lists in redis (https://github.com/FoundatioFx/Foundatio.Redis/blob/master/src/Foundatio.Redis/Queues/RedisQueue.cs#L449-L454):
1. Items waiting to be processed,
2. Items currently working (dequeue was called and the item is being worked on).
3. Items in dead letter (failed).
4. Items in wait list (Items that failed and need to be retried via retry policy), these get pushed back onto the 1 list (waiting to be processed) after the retry time has been met, there is a worker loop that does this).

I hope this helps, please let us know if you have any other questions, feedback or run into any issues. Also feel free to join our slack (link at the top of the readme) :).
