### ISSUE TITLE
Example for Work Item Job not working?

### ISSUE THREAD

**Issue by Gomez12** [FoundatioFx/Foundatio#143]
I am having trouble with the Work Item Job example.

On the following line : 
`new JobRunner(container.GetRequiredService<WorkItemJob>(), instanceCount: 2).RunInBackground();`
It complains that no service type WorkItemJob has been registered.
And that is correct, because in the rest of the example I also don't see it being registered.

But I also don't understand what to register. 

For additional info, i'm trying to implement it over redis, the goal is to have 1 workitemproducer and multiple job runners.

**Comment by niemyjski** [comment]
You need to register your work item job as well as work item handlers as shown here: https://github.com/FoundatioFx/Foundatio#sample-6  We may need to update the example to register the work item job. https://github.com/exceptionless/Exceptionless/blob/49c2e943830184e63941c0dfdc4c79a62ba9af05/src/Exceptionless.Core/Bootstrapper.cs#L167 Would you mind doing a pr for this. Does this help?
