### ISSUE TITLE
Q: System.Threading.Tasks.TaskCanceledException being thrown by job queue

### ISSUE THREAD

**Issue by lefig** [FoundatioFx/Foundatio#144]
Hi there,

I have a question after running the Redis sample - both the queue client and job. This works btw. But what I do see are regular System.Threading.Tasks.TaskCanceledException debug messages being displayed every second or so. 

These are generated here in TaskQueue :

private void StartWorking() {
            bool isTraceLogLevelEnabled = _logger.IsEnabled(LogLevel.Trace);
            if (isTraceLogLevelEnabled) _logger.LogTrace("Starting task background worker loop.");
            Task.Run(async () => {
                while (!_workLoopCancellationTokenSource.Token.IsCancellationRequested) {
                    try {
                        bool workerAvailable = await _semaphore.WaitAsync(1000, _workLoopCancellationTokenSource.Token).AnyContext();
                        if (!_queue.TryDequeue(out var task)) {
                            if (workerAvailable)
                                _semaphore.Release();

                            if (_queue.IsEmpty) {
                                try {
                                    using (var timeoutCancellationTokenSource = new CancellationTokenSource(10000))
                                    using (var dequeueCancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(_workLoopCancellationTokenSource.Token, timeoutCancellationTokenSource.Token)) {
                                        await ****_autoResetEvent.WaitAsync(dequeueCancellationTokenSource.Token).AnyContext();**
                                    }**
                                } catch (OperationCanceledException) { }
                            }

                            continue;
                        }

Is there a way to avoid this as best practice?

Thanks

**Comment by Gomez12** [comment]
To avoid this as a best practice i would say : Don't log at trace level...

Trace is the lowest bare bone level, where you want to get almost everything the code is doing.

**Comment by niemyjski** [comment]
Can you try this in the latest release as we got rid of the task queue and let us know if you are still seeing this. We log at the trace level because we want to see everything being outputted (e.g., tracing). In our development environments we log at the debug/info level and prod at the warn/info. Tracing should be for diagnostic purposes.

**Comment by lefig** [comment]
Sure thing. Will do.

Much obliged for the help.

**Comment by niemyjski** [comment]
Did updating resolve this issue?

**Comment by lefig** [comment]
No, I tried the latest (master) and version 8.0 releases. The exceptions are being thrown every 10 secs or so at RedisQueue.cs:
protected override async Task<IQueueEntry<T>> DequeueImplAsync(CancellationToken linkedCancellationToken) {
            bool isTraceLogLevelEnabled = _logger.IsEnabled(LogLevel.Trace);
            if (isTraceLogLevelEnabled) _logger.LogTrace("Queue {Name} dequeuing item...", _options.Name);
            long now = SystemClock.UtcNow.Ticks;

..............................................
..............................................
                try {
                    using (var timeoutCancellationTokenSource = new CancellationTokenSource(10000))
                    using (var dequeueCancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(linkedCancellationToken, timeoutCancellationTokenSource.Token)) {
                        await _autoResetEvent.WaitAsync(**dequeueCancellationTokenSource.Token**).AnyContext();
                    }
                } catch (OperationCanceledException) { }

Perhaps this is normal behaviour. But the exception is triggered on the above wait when the queue is empty.

**Comment by niemyjski** [comment]
Yes that is normal for it to be thrown and caught when there is nothing in the queue. But it shouldn't be blowing up inside of you application. Are you seeing that you are just seeing it logged or are you seeing it caught in your app? Is it a debugger setting like first chance exceptions?

**Comment by lefig** [comment]
Thank you for coming back to me. Yes, I noticed the stream of exception messages in the debug view and I have changed the exception settings to not break when the exception is thrown. Much appreciated:)

**Comment by lefig** [comment]
I have closed the issue although usually I would expect to see exceptions only in undefined behaviour as opposed to just having an empty queue. Thanks

**Comment by niemyjski** [comment]
I'm not aware of any better way to do this, if you have a way or anyone else reading this we are always listening and open to improvements. This code above has a timeout of 10 seconds that it will cause the reset event to throw, we do this because otherwise we might get into some crazy situation and deadlock. I feel it's better to wait for a period of time and self heal.
