### ISSUE TITLE
 Q: Queue job processor ProcessQueueEntryAsync

### ISSUE THREAD

**Issue by lefig** [FoundatioFx/Foundatio#146]
Hi there,

I would really appreciate asking a couple of questions about this great project. 

We are using the Redis queue implementation and during debug sessions I notice that  ProcessQueueEntryAsync continues to receive queue items for processing. The method returns JobResult.Success and I would expect that this item is removed from the processing queue. But every couple of seconds the same item is received or processing! What could explain that and how can I fix.

And what does the error "queue abandoned" mean? In some sessions I see that the queue gets into a locked state and I have to flush the redis db. Is there a way to delete the queue lock?

Thanks all

**Comment by niemyjski** [comment]
It should only be received once unless it gets abandoned, then it will be retried at a later time. If you could provide more information / sample or test that would be greatly appreciated. Abandoned means it could not be processed and it will be retried X times until it gets moved to dead letter. The queue lock is a specific key, I'd need to look at the Redis implementation to give you more information (best to log redis specific issues on that repository). Also do you have any logs?

**Comment by lefig** [comment]
Thank you for the most kind offer of help. I need to investigate this further. Unfortunately I cleared the error logs. But I think that the problem was probably related to the debug session. The architecture of our application is complicated by the fact that we use reflection to load a client dll and this fails when injecting the stackexchange redis library due missing dependencies. So we host the queue and job in a single process and communicate using zmq. This is fast btw. But the locks are strange and I can see them in Redis so I was hoping that there may be a timeout on the lock or means to remove. But I will take a further look. Thanks again for a great project

**Comment by niemyjski** [comment]
I like how the exceptionless app loads our dependencies (https://github.com/exceptionless/Exceptionless) we used to use reflection now we only call it from entry points. I'm going to close this issue and we'll reopen it if more information is provided on how to reproduce the issue.
