### ISSUE TITLE
Schedule Jobs?

### ISSUE THREAD

**Issue by TechInterMezzo** [FoundatioFx/Foundatio#148]
This is a question or maybe a feature request.

Is it possible to schedule jobs?
This would include recurring jobs and jobs that run only once at a specified time.

**Comment by ejsmith** [comment]
You can do CRON jobs. Take a look at this: https://github.com/FoundatioFx/Foundatio/blob/master/samples/Foundatio.HostingSample/Program.cs#L68

**Comment by TechInterMezzo** [comment]
Thank you for the fast answer.
That is all I need.
