### ISSUE TITLE
Add Nito.AsyncEx dependency

### ISSUE THREAD

**Issue by frabe1579** [FoundatioFx/Foundatio#150]
Now that Nito.AsyncEx has a stable release (5.0.0), I think is a good idea to remove old code and add a dependency to the original NuGet packages.

**Comment by niemyjski** [comment]
I'd rather keep dependencies like this that rarely change and are super small internal. We've also had lots of versioning issues with this package too :\. Would you mind doing a pr for updating this via source import?

**Comment by ejsmith** [comment]
Yeah, we should update the source.

**Comment by frabe1579** [comment]
Ok i've cloned the repo, update the code and added Nito.AsyncEx.Coordination as dependency. Everything is ok, all test run (that ones I can run) successfully but there is the omnipresent problem: all Nito.AsyncEx assemblies does not have a strong name. I've read some issues discussing that on Nito.AsyncEx repo, and there is no plan (and maybe no hope) to get strong named assemblies from original sources.
So, I don't know which is the better road to take (and if there is one).
Any suggestions?

**Comment by niemyjski** [comment]
We should be importing the source code (clone, copy to folder, change namespace if required, make classes internal), so there would be no dependencies or csproj changes. I thought we have a script for this but maybe not.

**Comment by niemyjski** [comment]
Is there any updates on this?

**Comment by niemyjski** [comment]
I made a pr for this and will close this issue :)
