### ISSUE TITLE
Simple Question about Scheduling jobs

### ISSUE THREAD

**Issue by Roneri75** [FoundatioFx/Foundatio#154]
Hi

We are building an app where we need to schedule jobs, .exe executions mostly , and i'm wondering if it is possible to use the cron schedule in FundationFX to run a set of jobs in a sequential order?
And is it possible to have multiple cron scheduls on the same set of jobs?

**Comment by niemyjski** [comment]
Hello,

Yes you can define a cron job as shown here (https://github.com/FoundatioFx/Foundatio/blob/master/samples/Foundatio.HostingSample/Program.cs#L69) and schedule them out to run at a set time, I don't know if we respect sequential order if you set them all to run at the same time, it may happen in parallel (can you try this out and let us know).

I'm not too sure off the top of my head but you could try adding the cron job multiple times and let us know.
