### ISSUE TITLE
[Feature] Search block

### ISSUE THREAD

**Issue by Jogai** [FoundatioFx/Foundatio#156]
Idea for another building block. Implementations could be ElasticSearch, Azure Search, Lucene, SQL FullText etc.

**Comment by niemyjski** [comment]
We have this with the https://github.com/foundatiofx/foundatio.repositories repository where we have an implementation for Elasticsearch. It would be nice to support additional implementations. Although the more I think about it, I like that the queries are implemented in a repository and not leaked throughout the code making it injectable/testable. But I almost feel like we should just use the client libraries as you more than likely never change the backend out. 

If this doesn't answer your question/feature request please let us know.
