### ISSUE TITLE
Error While Installing package from NuGet

### ISSUE THREAD

**Issue by AminuBishir** [FoundatioFx/Foundatio#176]
I was trying to install this package into my application but I got an installation error as thus:
```
install-package : Could not install package 'Foundatio 8.1.2126'. You are trying to 
install this package into a project that targets '.NETFramework,Version=v4.6', but the package
 does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author.
```

Please what am I doing wrong? and
What can I do to fix this?

Info:
It's Desktop winform app that uses EF 6

**Comment by niemyjski** [comment]
We target .NET Standard 2.0 so it should be working. It could be your version of Visual Studio / NuGet tooling, are you on the latest version? Also I'd recommend upgrading to latest version of .NET if possible as they've made many improvements for consuming .net standard libraries.

**Comment by AminuBishir** [comment]
Thanks for you response.
I'll try out your suggestions.

**Comment by ejsmith** [comment]
Your app needs to be running at least .net 4.6.1 framework in order to work with .net standard 2.0 assemblies.

**Comment by niemyjski** [comment]
I'm going to close this as @ejsmith answered this question. If you run into any issues please let us know.
