### ISSUE TITLE
Similar classes in different packages

### ISSUE THREAD

**Issue by saleembasit** [FoundatioFx/Foundatio#192]
Hi

I am a noob here, so please be gentle.

I wanted to use second level crons in my project. I noticed that the current code is ignoring Cronos CronFormat.IncludesSeconds options. When trying to add this option, I noticed the same/similar classes in .Hosting and .Extensions.Hosting packages.

Please guide me in which classes should I add my changes.

Regards

**Comment by niemyjski** [comment]
I'd add them to both, one is for .NET Core 2.0 and the other is for .NET Core 3.0 (extensions). The changes should be pretty easy to just copy and paste to the other project. I hope this helps.
