### ISSUE TITLE
multiple keys locking per AcquireAsync 

### ISSUE THREAD

**Issue by GoNextGroup** [FoundatioFx/Foundatio#196]
Hello. 

Is here possible to lock multiple keys by one  AcquireAsync call?
The case it can be used: lock different tables of the database in EF Core, for example.

Thank you.

**Comment by niemyjski** [comment]
What would you expect to get back a collection of locks? What if one or more can't be acquired? I think this introduces a lot of added complexity.  For your example, there are architecture patterns for handling this like  two-phase commit distributed transactions, or a queue for writes which I feel you may be trying todo?

**Comment by GoNextGroup** [comment]
> What would you expect to get back a collection of locks? What if one or more can't be acquired? I think this introduces a lot of added complexity. For your example, there are architecture patterns for handling this like two-phase commit distributed transactions, or a queue for writes which I feel you may be trying todo?

Let me explain my idea.
Imagine we have same client orders which can be collected in the routes (some orders per route). And I have same services which work with orders and routes. Orders and Routes are placed independently in the different tables. And we need to lock access for services which work with orders and routes both when one service works with data from, for example, orders table.
So, I can "ask" locker for each table/subtable or make a "bulk" request for locking. I think It do not need to implement WhenAny/WhenAll paradigm in the first time - AcquireAsync just need to lock all passed keys per time and ReleaseAsync should return back all keys. In the future, of course, It could be great to have ReleaseAsync(ICollection<string> keys) for partial releasing (it can implove performance hard when we work with EF Core).

Thank you.

**Comment by niemyjski** [comment]
This will go out in the next release! Thanks for submitting the feature request and being patient. https://github.com/FoundatioFx/Foundatio/commit/a759aabcb2079d74ffad029a6204061cd1390ce1
