### ISSUE TITLE
Inconsistent cache descriptions in README

### ISSUE THREAD

**Issue by Leon99** [FoundatioFx/Foundatio#209]
From README:
> HybridCacheClient: This cache implementation uses the InMemoryCacheClient and uses the IMessageBus to keep the cache in sync across processes.

> RedisHybridCacheClient: This cache implementation uses both the RedisCacheClient and InMemoryCacheClient implementations and uses the RedisMessageBus to keep the in memory cache in sync across processes. This can lead to huge wins in performance as you are saving a serialization operation and call to Redis if the item exists in the local cache.

Issues here:
1. HybridCacheClient uses not just InMemoryCacheClient but both an ICacheClient and InMemoryCacheClient. Description of RedisHybridCacheClient mentions it but HybridCacheClient's doesn't. At first, I thought that this implementation doesn't need a distributed cache at all, but, upon checking the source, I realised that's not the case.

2. I suspect the note about "This can lead to huge wins in performance as you are saving a serialization operation and call to Redis if the item exists in the local cache." applies to HybridCacheClient, not to RedisHybridCacheClient specifically.

I'm happy to submit a PR with fixes for those if I have a confirmation that it makes sense.

**Comment by ejsmith** [comment]
Yes, that makes sense. Happy to take a PR!
