### ISSUE TITLE
cron jobs

### ISSUE THREAD

**Issue by T1000v2** [FoundatioFx/Foundatio#235]
Does your code allow to easy run simple "cron" tasks from memory periodic e.g. every day at same hour?

**Comment by ejsmith** [comment]
Yes, take a look at https://github.com/FoundatioFx/Foundatio/blob/master/samples/Foundatio.HostingSample/Program.cs#L78

**Comment by T1000v2** [comment]
Thanks, have you got something simple which works with db? I don't want to use e.g. quartz net and so on, but want to have it later to support clustered app and in memory could not be enough.

**Comment by ejsmith** [comment]
@T1000v2 no, we don't have any support for persisted / distributed cron jobs currently.
