### ISSUE TITLE
CacheLockProvider throws format exception when it fails to acquire lock and trace logging is enabled

### ISSUE THREAD

**Issue by Seadoo2017** [FoundatioFx/Foundatio#237]
CacheLockProvider.cs line 81:
 _logger.LogTrace("Failed to acquire lock {Resource.", resource);
Should be changed to
 _logger.LogTrace("Failed to acquire lock {Resource}", resource);
So it will not throw format exception on logging and log the correct message

Thanks! :)

**Comment by niemyjski** [comment]
Thanks for reporting this and letting us know about this!!!
