### ISSUE TITLE
Redis and InMemory implementations for RenewLock()

### ISSUE THREAD

**Issue by jamie94bc** [FoundatioFx/Foundatio#24]
Already implemented in Azure Service Bus and Storage Queues.

Redis: https://github.com/exceptionless/Foundatio/src/Redis/Queues/RedisQueue.cs#L297
InMemory: https://github.com/exceptionless/Foundatio/blob/master/src/Core/Queues/InMemoryQueue.cs#L174

**Comment by ejsmith** [comment]
Closing this as it has been implemented now.

https://github.com/FoundatioFx/Foundatio/blob/master/src/Foundatio/Queues/InMemoryQueue.cs#L160
https://github.com/FoundatioFx/Foundatio.Redis/blob/master/src/Foundatio.Redis/Queues/RedisQueue.cs#L287
