### ISSUE TITLE
[Not a Bug] Discord Channel? I want to commit some example code

### ISSUE THREAD

**Issue by jeffward01** [FoundatioFx/Foundatio#286]
Hello!!

I have some example code for all of the implementations of Messages, and Queues (minus the 'Handler', I cant get that to work, and would love to share my sandbox demo code with someone to discuss it.

I plan to add more examples, I also have an example for a 'Gofer.NET' style, many workers 'out of process' workers using Redis.

I have some questions also about Metrics, I am strugging to understand what exactly the 'Metrics' do. 

Anyways, I saw you guys are on Discord, but I could not find the server URL link. I also sent a chat message to your robot on your website.

Very cool library!! 

If you can share your Discord URL, that would be great

**Comment by niemyjski** [comment]
Here is a link to our discord: https://discord.gg/6HxgFCx See you soon and we'll talk about any questions or feedback that you have!
