### ISSUE TITLE
Examples for DependencyInjection

### ISSUE THREAD

**Issue by U52284** [FoundatioFx/Foundatio#288]
I'm currently trying to integrate IFileStorage but I'm missing a good example on how to use it in DI. Is there an out of the box extension to register one or another implementation of the interface? I have an enumeration of the providers I want to provide and register one or the other. Also to make use of the scoped file storage in combination with the providers.

Or do I have to do all myself? Just dont want to wast time on something already existing.

Thanks in advance

**Comment by ejsmith** [comment]
If you are wanting multiple variations of IFileStorage, you'd need to handle that yourself. What we've typically done is create a derived interface like IMyFileStorage that inherited IFileStorage and then you'll have to derived from the implementation class and implement that interface as well.

**Comment by U52284** [comment]
Thought about that. But also I was sure I'm not the first one encountering that one or maybe I havent seen a build in mechanism that is already prepared for that. It seems this would be a very good thing beeing available out of the box.

**Comment by ejsmith** [comment]
There isn’t really a great solution to this. It’s really a named instance DI issue which is a feature getting built into .NET 8. If you have other ideas, feel free to discuss or create a PR.

**Comment by U52284** [comment]
I will check if I can setup something in the next week or so. For now thats enough input for me thank you.
