### ISSUE TITLE
SaveFile Overload with Stream

### ISSUE THREAD

**Issue by U52284** [FoundatioFx/Foundatio#289]
Hi

I'm currently trying to use Foundatio.Storage to read files from a folder, putting them into a zip archive and saving them again.

The problem is now, that there is no overload for SaveFileAsync where I'm getting a stream that lets me bit by bit write files and content into the target stream. That means currenlty I have only one option, that is creating a memory stream, writing everything in it and save that stream with SaveFileAsync. But that means, That I need al the content in memory before I can save it to the disk. And that is on one side very limiting and unnecessary since streams are made to be forward content bit by bit. But the current SaveFileAsync does not allow that.

Here my example code with my extension I new implemented that us working now with inmemory stream

```
public async Task ArchiveAsync(string sourceDirectory, string targetArchive, CancellationToken cancellationToken)
    {
        try
        {
            using var archiveFileStream = _fileStorage.GetCreateFileStream(targetArchive);
            using var archive = new ZipArchive(archiveFileStream, ZipArchiveMode.Create);

            var files = await _fileStorage.GetFileListAsync($"{sourceDirectory}/*", null, cancellationToken);
            var paths = files
                .ToDictionary(
                    x => x.Path
                        .Replace(Path.DirectorySeparatorChar, '/')
                        .Replace(sourceDirectory, "", StringComparison.Ordinal)
                        .TrimStart('/'),
                    x => x.Path);

            foreach (var path in paths)
            {
                var entry = archive.CreateEntry(path.Key);
                using var fileStream = await _fileStorage.GetFileStreamAsync(path.Value, cancellationToken);
                using var entryStream = entry.Open();

                fileStream.CopyTo(entryStream);
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error while archive directory {Archive}", sourceDirectory);
            throw;
        }
    }
```

Is there something like that in progress, or should I make a proposal myself?

Kind regards

**Comment by ejsmith** [comment]
Yeah, we definitely need this. Just haven't gotten the time to do it yet. Do you want to submit a PR?

**Comment by garcipat** [comment]
I will see what I can do

**Comment by ejsmith** [comment]
Yeah, we can close this. Thanks!
