### ISSUE TITLE
locks in async context

### ISSUE THREAD

**Issue by garcipat** [FoundatioFx/Foundatio#293]
I discovered that in the file storage a lock object is used but the methods are actually asynchroneous.

Would it make sense to switch to a semaphore slim there instead?
see here https://github.com/FoundatioFx/Foundatio/blob/871be38c6b4b0ab19e86041f1f8714557428fbf8/src/Foundatio/Storage/FolderFileStorage.cs#L15

**Comment by niemyjski** [comment]
Nice catch, we have an async lock we can use instead. Just search for AsyncLock. Would you mind submitting a pr for this?

**Comment by garcipat** [comment]
I will check that then.
