### ISSUE TITLE
Feature: Skip Missed CRON schedule

### ISSUE THREAD

**Issue by pinkfloydx33** [FoundatioFx/Foundatio#317]
We are using distributed CRON jobs. If the workers go offline for an extended period of time, when they come back online they trigger for all missed instances of the job. We'd prefer that instead of running _all_ the instances, it simply runs the _next scheduled one_.

We have a job that runs every five minutes. We had an outage in our dev stack recently and were down for several hours. When we came back online, it took an incredibly long time for the worker to "catch back up", as it triggered for each missed instance. In our case, that first run was enough, and every invocation that followed wasted processing power and time to essentially do nothing. (This particular worker triggers a queue job per tenant. Each of those then fired, causing scale ups in AKS, the jobs executed only to find out they had nothing to do/process, and then this rinse-repeated for a very long time).

I eventually (after about an hour) figured out that I could connect to the redis cache and clear the tracking keys such that the worker thought it had never run before, with the next invocation finally stopping. 

It would be nice to have an option to control this if you don't care about missed instances. It would also help our local development workflows where we might have the job powered off purposely.

**Comment by ejsmith** [comment]
Yeah, that's definitely not ideal. Thinking maybe we could be checking to see if we are more than 1 instance behind and we would run 1 instantly because we are behind, but then we would jump after that to be up to date.

**Comment by ejsmith** [comment]
Pushed a commit that will run immediately if the schedule is past due and then will resume normal cron schedule without running a bunch of times in a row to try and catch up.

**Comment by pinkfloydx33** [comment]
Cool thanks!
