### ISSUE TITLE
Add reentrant read-write lock

### ISSUE THREAD

**Issue by send2vinnie** [FoundatioFx/Foundatio#34]
Add reentrant read-write lock to get better performance while doing read only operations.
[https://github.com/Netflix/curator/wiki/Shared-Reentrant-Read-Write-Lock](https://github.com/Netflix/curator/wiki/Shared-Reentrant-Read-Write-Lock)

**Comment by ejsmith** [comment]
Would love to see a pull request for this!

**Comment by niemyjski** [comment]
@send2vinnie would you mind creating a pr for this?

**Comment by ejsmith** [comment]
Going to close this as we don't have any plans to implement this currently. Would still love to see a PR if you are interested in implementing it.
