### ISSUE TITLE
Add integration with Microsoft's logging system

### ISSUE THREAD

**Issue by SukharevAndrey** [FoundatioFx/Foundatio#74]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging
Microsoft is using their simple standardized and expandable logging library - https://github.com/aspnet/Logging.
It would be great if you implement some sort of integration between Foundatio's logging library and Microsoft's one to see foundatio log messages in unified way.

**Comment by niemyjski** [comment]
We'd love to have an integration for this, would you mind submitting a pr for this?

**Comment by niemyjski** [comment]
We've completely adopted the Microsoft logging extensions in v6 (release notes incoming).
