### ISSUE TITLE
Send work item failed progress messages

### ISSUE THREAD

**Issue by niemyjski** [FoundatioFx/Foundatio#76]
We don't send a progress message when a work item fails. What should the status be?

**Comment by jamie94bc** [comment]
If we were to stick with the current `WorkItemStatus` model then I think setting the integer `Progress` property to `-1` with an appropriate message would be clear enough.

**Comment by niemyjski** [comment]
@jamie94bc good point :)

**Comment by akshay-zz** [comment]
Hi @niemyjski , I would like to take this issue. Just want to understand things. In `WorkItemJob.ProcessAsync` in case of an exception, we want to report the status as `-1` with a proper message.

**Comment by niemyjski** [comment]
Awesome! Yeah, I think that works for a solution.
