### ISSUE TITLE
Do you have any plans to introduce support for AWS SQS/SNS?

### ISSUE THREAD

**Issue by jsancho** [FoundatioFx/Foundatio#93]
Just like there's storage support for Azure Blob and S3, it would be quite nice to have the opportunity to be cloud-agnostic in what regards to Queues.

**Comment by jamie94bc** [comment]
We did have a PR for SQS which was merged https://github.com/exceptionless/Foundatio/pull/85, but the target branch (release/5.1.0) seems to have disappeared, @niemyjski?

**Comment by niemyjski** [comment]
We are working on SQS queues and Cloudwatch metrics in the cloud watch branch, we have a few apps that will be using both of these in production and they are available in our nightly nuget feed on myget: https://www.myget.org/gallery/exceptionless We currently don't have support for SQS/SNS but would be more than happy to accept a pr for this :)

**Comment by jsancho** [comment]
sorry, getting a bit confused.
You mean that you are adding SQS support on a feature branch for now, but that SNS is not in the horizon? Hence, why you wouldn't mind welcoming a PR?

**Comment by ejsmith** [comment]
We have the SQS queue implementation working pretty well now. We have a couple apps using it. I would love to see a pull request for supporting SNS. I think SNS would be a IMessageBus implementation, correct?

**Comment by jsancho** [comment]
Our most urgent need here is to integrate with SQS, so that's actually great news.
SNS is not far on the horizon though, so if I can get things to work with our setup.
I don't see why we couldn't help out with the SNS implementation 👍

**Comment by ejsmith** [comment]
I'm closing this as we have SQS support now. If you want to add a request for SNS separately or even better submit a PR that would be great!
