### ISSUE TITLE
Error in documentation, JobRunContext should be JobContext

### ISSUE THREAD

**Issue by rozifus** [FoundatioFx/Foundatio#96]
It looks like in the Job sample in the documentation
https://github.com/FoundatioFx/Foundatio#sample-4

The parameter to RunInternalAsync should be of type JobContext to match
https://github.com/FoundatioFx/Foundatio/blob/master/src/Foundatio/Jobs/JobBase.cs

**Comment by niemyjski** [comment]
Would you mind submitting a pr for this :)?

**Comment by rozifus** [comment]
Sure thing :)

**Comment by rozifus** [comment]
P
#97

**Comment by niemyjski** [comment]
Thank you!!!!
