### ISSUE TITLE
Create strong named nuget packages

### ISSUE THREAD

**Issue by ytkaczyk** [FoundatioFx/Foundatio#99]
Would it be possible for you to publish strong named nuget packages which foundation depdending on strong named/signed package when they are available, for instance StackExchange.Redis.StrongName. This would be helpful for using Foundation along other packages such as SignalR.Redis.

I hope you will consider doing this.

**Comment by niemyjski** [comment]
We'd be more than happy to accept a pr which updates foundatio packages to be strong named.

@ejsmith should we create a new key or reuse https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless.snk

**Comment by ytkaczyk** [comment]
Thank you. We will look into doing this in the near future and let you know.

**Comment by niemyjski** [comment]
This was merged in! Thanks for the PR

**Comment by ytkaczyk** [comment]
You are welcome. We are glad we could contribute.
